// Sabian Symbols — 360 degrees, 1 per degree
// Source: public domain interpretations by Marc Edmund Jones / Dane Rudhyar
import type { Lang } from './localize'

const SABIAN_EN: string[] = [
  // Aries 1-30
  "A woman has risen out of the ocean, a seal is embracing her",
  "A comedian reveals human nature",
  "A cameo profile of a man in the outline of his country",
  "Two lovers are strolling through a secluded walk",
  "A triangle with wings",
  "A square brightly lighted on one side",
  "A man succeeds in expressing himself in two realms at once",
  "A woman's hat with streamers blown by the east wind",
  "A crystal gazer",
  "A man teaching new forms for old symbols",
  "The ruler of a nation",
  "A flock of wild geese",
  "A bomb which failed to explode is now safely concealed",
  "A serpent coiling near a man and a woman",
  "An Indian weaving a blanket",
  "Brownies dancing in the setting sun",
  "Two prim spinsters sitting together in silence",
  "An empty hammock",
  "The magic carpet of Oriental imagery",
  "A young girl feeding birds in winter",
  "A pugilist entering the ring",
  "The gate to the garden of all fulfilled desires",
  "A woman in pastel colors carrying a heavy and valuable but veiled load",
  "An open window and a net curtain blowing into a cornucopia",
  "A double promise reveals its inner and outer meanings",
  "A man possessed of more gifts than he can express",
  "Through imagination a lost opportunity is regained",
  "A large disappointed audience",
  "A celestial choir singing",
  "A duck pond and its brood",
  // Taurus 1-30
  "A clear mountain stream",
  "An electrical storm",
  "Natural steps lead to a lawn of clover in bloom",
  "The rainbow's pot of gold",
  "A widow at an open grave",
  "A bridge being built across a gorge",
  "A woman of Samaria comes to draw water",
  "A sleigh without snow",
  "A fully decorated Christmas tree",
  "A reflection of a man's being upon the still mirror of a pool",
  "A woman watering flowers in her garden",
  "Window-shoppers",
  "A man handling baggage",
  "Shellfish groping and children playing",
  "Magnetic fish under the polar ice",
  "An old man attempting vainly to reveal the mysteries",
  "A symbolical battle between swords and torches",
  "A woman airing a linen bag through the sunny window",
  "A newly formed continent",
  "Wisps of winglike clouds streaming across the sky",
  "A finger pointing in an open book",
  "A white dove over troubled waters",
  "A jewelry shop",
  "An Indian girl introduces her white lover to her assembled tribe",
  "A vast public park",
  "A Spaniard serenading his beloved",
  "A squaw selling beads",
  "A woman pursued by mature romance",
  "Two cobblers working at a table",
  "A peacock parading on an ancient lawn",
  // Gemini 1-30
  "A glass-bottomed boat reveals undersea wonders",
  "Santa Claus filling stockings furtively",
  "The garden of the Tuileries in Paris",
  "Holly and mistletoe reawaken old memories of Christmas",
  "A radical magazine or publication",
  "Drilling for oil",
  "An old-fashioned well with the purest and coldest of waters",
  "Aroused strikers surround a factory",
  "A quiver filled with arrows",
  "An airplane diving towards the earth",
  "Newly opened lands offer the pioneer new opportunities for experience",
  "A black slave-girl demands her rights of her mistress",
  "A great musician at his piano",
  "A conversation by telepathy",
  "Two Dutch children talking to each other, exchanging knowledge",
  "A woman activist in an emotional speech dramatizing her cause",
  "The head of a robust youth changes into that of a mature thinker",
  "Two figures in the night one of which is a silhouette",
  "A large archaic volume reveals a traditional wisdom",
  "A modern cafeteria displays an abundance of food products of various regions",
  "A labor demonstration",
  "A barn dance",
  "Three fledglings in a nest high in a tree",
  "Children skating on ice",
  "A man trimming palms",
  "Frost-covered trees against winter skies",
  "A gypsy emerging from the forest wherein her tribe is encamped",
  "Through bankruptcy society gives to an overburdened individual the opportunity to begin again",
  "The first mockingbird of spring",
  "A parade of bathing beauties before large beach crowds",
  // Cancer 1-30
  "On a ship the sailors lower an old flag and raise a new one",
  "A man on a magic carpet hovers over a large area of land",
  "An arctic explorer leads a reindeer through icy canyons",
  "A cat arguing with a mouse",
  "An automobile wrecked by a train",
  "Game birds feathering their nests",
  "Two fairies on a moonlit night",
  "Rabbits dressed in clothes and on parade",
  "A tiny nude miss reaching in the water for a fish",
  "A large diamond not completely cut",
  "A clown caricaturing well-known personalities",
  "A Chinese woman nursing a baby whose aura reveals him to be the reincarnation of a great teacher",
  "One hand slightly flexed with a very prominent thumb",
  "A very old man facing a vast dark space to the northeast",
  "In a sumptuous dining hall guests relax after partaking of a huge banquet",
  "A man before a square with a manuscript scroll before him",
  "The seed grows into knowledge and life",
  "A hen scratching the ground to find nourishment for her progeny",
  "A priest performing a marriage ceremony",
  "Gondoliers in a serenade",
  "A famous singer is proving her virtuosity during an operatic performance",
  "A young woman awaiting a sailboat",
  "Meeting of a literary society",
  "A woman and two men castaways on a small island of the South Seas",
  "A will-o-the-wisp",
  "Contentment and happiness in luxury people riding on a merry-go-round",
  "A storm in a canyon",
  "A modern Pocahontas",
  "A Muse weighing twins",
  "A daughter of the American Revolution",
  // Leo 1-30
  "Under emotional stress blood rushes to a man's head",
  "An epidemic of mumps",
  "A woman having her hair done",
  "A formally dressed elderly man and young girl",
  "Rock formations tower over a deep canyon",
  "A conservative, old-fashioned lady is confronted by a hippie girl",
  "The constellations of stars shine brilliantly in the night sky",
  "A Bolshevik propagandist",
  "Glass blowers shape beautiful vases with their controlled breathing",
  "Early morning dew sparkles as sunlight floods the field",
  "Children play on a swing hanging from the branches of a huge oak tree",
  "An evening lawn party of adults",
  "An old sea captain rocking on the porch of his cottage",
  "The human soul, in its eagerness for new experiences, seeks embodiment",
  "A pageant",
  "Sunshine just after a storm",
  "A volunteer church choir makes a social event of rehearsal",
  "A teacher of chemistry",
  "A houseboat party",
  "The Zuni sun worshippers",
  "Chickens intoxicated",
  "A carrier pigeon fulfilling its mission",
  "A bareback rider in a circus",
  "Totally concentrated upon inner spiritual attainment, a man is sitting in a state of complete neglect of bodily appearance and cleanliness",
  "A large camel crossing a vast and forbidding desert",
  "After the storms of winter, a serene spring scene enacts itself",
  "Daybreak — the luminescence of dawn in the eastern sky",
  "Many little birds on a limb of a big tree",
  "A mermaid emerges from the ocean waves ready for rebirth in human form",
  "An unsealed letter",
  // Virgo 1-30
  "In a portrait, the significant features of a man's head are artistically emphasized",
  "A large white cross, upraised",
  "Two angels bringing protection",
  "A colored child playing with white children",
  "A man dreaming of fairies",
  "A merry-go-round",
  "A harem",
  "First dancing instruction",
  "A man making a futurist drawing",
  "Two heads looking out and beyond the shadows",
  "A boy molded in his mother's aspirations for him",
  "A bride with her veil snatched away",
  "A strong hand supplanting political hysteria",
  "A family tree",
  "A fine lace ornamental handkerchief",
  "An orangutan",
  "A volcanic eruption",
  "A ouija board",
  "A swimming race",
  "A caravan of cars headed to the west coast",
  "A girls' basketball team",
  "A royal coat of arms",
  "A lion tamer rushes fearlessly into the circus arena",
  "Mary and her white lamb",
  "A flag at half-mast in front of a large public building",
  "A boy with a censer serves the priest near the altar",
  "Aristocratic elderly ladies drinking afternoon tea in a wealthy home",
  "A bald-headed man who has seized power",
  "A man gaining secret knowledge from an ancient scroll he is reading",
  "A false call unheard in attention to immediate service",
  // Libra 1-30
  "In a collection of perfect specimens of many biological forms, a butterfly displays the beauty of its wings, which vary from the general type",
  "The light of the sixth race transmuted to the seventh",
  "The dawn of a new day reveals everything changed",
  "A group of young people sit in spiritual communion around a campfire",
  "A man teaching the true inner knowledge of the new world to his students",
  "The ideals of a man abundantly crystallized",
  "A woman feeding chickens and protecting them from the hawks",
  "A blazing fireplace in a deserted home",
  "Three old masters hanging in a special room in an art gallery",
  "Having passed safely through narrow rapids, a canoe reaches calm waters",
  "A professor peering over his glasses at his students",
  "Miners are surfacing from a deep coal mine",
  "Children blowing soap bubbles",
  "A noon siesta",
  "Circular paths",
  "After a storm a boat landing stands in need of reconstruction",
  "A retired sea captain watches ships entering and leaving the harbor",
  "Two men placed under arrest give an accounting for their acts before the tribunal of society",
  "A gang of robbers in hiding",
  "A rabbi performing his duties",
  "A crowd upon the beach",
  "A child giving birds a drink at a fountain",
  "Chanticleer's voice heralds the rising sun with exuberance",
  "A butterfly with a third wing on its left side",
  "The sight of an autumn leaf brings to a pilgrim the sudden revelation of the mystery of life and death",
  "An eagle and a large white dove turning one into the other",
  "An airplane sails, high in the clear sky",
  "A man in deep gloom. Unnoticed, angels come to his aid",
  "Humanity seeking to span the bridge of knowledge",
  "Three mounds of knowledge on a philosopher's head",
  // Scorpio 1-30
  "A crowded sightseeing bus on a city street",
  "A delicate bottle of perfume lies broken, releasing its fragrance",
  "A house-raising party in an old-fashioned American community lends its effort to the building of a man's house",
  "A youth carrying a lighted candle",
  "A massive rocky shore",
  "A gold rush tears men away from their native soil",
  "Deep-sea divers",
  "The silvery moon shining across a beautiful gem of a lake",
  "A dentist at work",
  "A fellowship supper reunites old comrades",
  "A drowning man is being rescued",
  "An embassy ball",
  "An inventor performs a laboratory experiment",
  "Telephone linemen at work installing new connections",
  "Children playing around five mounds of sand",
  "A girl's face breaking into a smile",
  "A woman, fecundated by her own spirit, is 'great with child'",
  "A woods rich in autumn coloring",
  "A parrot listening and then talking, repeats a conversation he has overheard",
  "A woman draws away two dark curtains closing the entrance to a sacred path",
  "Obeying his conscience, a soldier resists orders",
  "Hunters starting out for ducks",
  "A bunny metamorphosed into a fairy",
  "Crowds coming down the mountain to listen to one man",
  "An x-ray photograph",
  "Indians making camp in new territory",
  "A military band on the march",
  "The king of the fairies approaching his domain",
  "An Indian squaw pleading to the chief for the lives of her children",
  "The Halloween jester",
  // Sagittarius 1-30
  "Retired army veterans gather to reawaken old memories",
  "The ocean covered with whitecaps",
  "Two men playing chess",
  "A little child learning to walk with the encouragement of his parents",
  "An old owl up in a tree",
  "A game of cricket",
  "Cupid knocking at the door",
  "Within the depths of the earth new elements are being formed",
  "A mother with her children on stairs",
  "A theatrical representation of a golden-haired goddess of opportunity",
  "The lamp of physical enlightenment at the left temple",
  "A flag that turns into an eagle that crows",
  "A widow's past is brought to light",
  "The pyramids and the sphinx",
  "The groundhog looking for its shadow on ground-hog day",
  "Seagulls watching a ship",
  "An Easter sunrise service draws a large crowd",
  "Tiny children in sunbonnets",
  "Pelicans menaced by the behavior and refuse of men seek safer areas for bringing up their young",
  "In an old-fashioned northern village men curl the heavy stone",
  "A child and a dog wearing borrowed eyeglasses",
  "A general accepting defeat gracefully",
  "Immigrants entering a new country",
  "A bluebird standing at the door of the house",
  "A chubby boy on a hobbyhorse",
  "A flag bearer in a battle",
  "A sculptor at his work",
  "An old bridge over a beautiful stream is still in constant use",
  "A fat boy mowing the lawn",
  "The Pope blessing the faithful",
  // Capricorn 1-30
  "An Indian chief claims power from the assembled tribe",
  "Three stained-glass windows in a Gothic church, one damaged by war",
  "The human soul receptive to growth and understanding",
  "A group of people outfitting a large canoe at the start of a journey by water",
  "Indians — some rowing a canoe and others dancing a war dance in it",
  "Ten logs lie under an archway leading to darker woods",
  "A veiled prophet speaks, seized by the power of a god",
  "In a sunlit home, domesticated birds sing joyously",
  "An angel carrying a harp",
  "An albatross feeding from the hand of a sailor",
  "A large group of pheasants on a private estate",
  "An illustrated lecture on natural science reveals little-known aspects of life",
  "A fire worshipper meditates on the ultimate realities of existence",
  "An ancient bas-relief carved in granite remains a witness to a long-forgotten culture",
  "In a hospital, the children's ward is filled with toys",
  "Boys and girls in gymnasium suits",
  "A repressed woman finds psychological release in nudism",
  "The Union Jack flag flies from a new British warship",
  "A child of about five with a huge shopping bag",
  "A hidden choir singing during a religious service",
  "A relay race",
  "By accepting defeat gracefully, a general reveals nobility of character",
  "Two awards for bravery in war",
  "A woman entering a convent",
  "An oriental rug dealer in a store filled with precious ornamental rugs",
  "A water sprite",
  "Pilgrims climbing the steep steps leading to a mountain shrine",
  "A large aviary",
  "A woman reading tea leaves",
  "A secret business conference",
  // Aquarius 1-30
  "An old adobe mission in California",
  "An unexpected thunderstorm",
  "A deserter from the navy",
  "A Hindu pundit reveals his caste by his sandals",
  "A council of ancestors has been called to guide a man",
  "A performer of a mystery play",
  "A child is seen being born out of an egg",
  "Beautifully gowned wax figures on display",
  "A flag is seen turning into an eagle",
  "A man who had for a time become the embodiment of a popular ideal is made to realize that as a person he is not this ideal",
  "During a silent hour, a man receives a new inspiration which may change his life",
  "People on stairs graduated upwards",
  "A barometer",
  "A train entering a tunnel",
  "Two lovebirds sitting on a fence and singing happily",
  "A big businessman at his desk",
  "A watchman signaling in the night",
  "A man unmasked",
  "A forest fire is being subdued by the use of water, chemicals and sheer muscular energy",
  "A large white dove bearing a message",
  "A woman disappointed and disillusioned, courageously facing a seemingly empty life",
  "A rug placed on a floor for children to play",
  "A big bear sitting down and waving all its paws",
  "A man turning his back on his passions teaches from his experience",
  "A butterfly with the right wing more perfectly formed",
  "A hydrometer",
  "An ancient pottery bowl filled with fresh violets",
  "A tree felled and sawed to ensure a supply of wood for the winter",
  "Butterfly emerging from chrysalis",
  "Moonlit fields, once babylon, are now blooming white",
  // Pisces 1-30
  "A public market",
  "A squirrel hiding from hunters",
  "A penitent man is confessing his sins to a priest",
  "Heavy traffic on a narrow isthmus",
  "A church bazaar",
  "Officers on dress parade",
  "Illumined by a shaft of light, a large cross lies on rocks surrounded by sea mist and tiny white-capped waves",
  "A girl blowing a bugle",
  "The race begins: intent on outdistancing his rivals, a jockey spurs his horse to great speed",
  "An aviator in the clouds",
  "Men seeking illumination are striving to perse the mysteries, sitting in a circle and using a ouija board",
  "In the sanctuary of an occult brotherhood, newly initiated members are being examined and their character tested",
  "A sword, used in many battles, is now in a museum",
  "A woman wrapped in fox fur",
  "An officer preparing men for a long journey by land",
  "In the quiet of his study a creative individual experiences a flow of inspiration",
  "An Easter promenade",
  "In a huge tent a famous revivalist conducts his meeting with a spectacular performance",
  "A master instructing his disciples",
  "A table set for an evening meal",
  "Under the watchful and kind eye of a Chinese servant, a girl fondles a little white lamb",
  "The gate to the garden of desire",
  "A 'materializing' medium giving a seance",
  "On a small island surrounded by the vast expanse of the sea, people are having a barbecue by the water",
  "The purging of the priesthood",
  "Watching the very thin moon crescent appearing at sunset different people realize that the time has come to go ahead with their different projects",
  "The harvest moon illuminates a clear autumnal sky",
  "A fertile garden under the full moon reveals a variety of full-grown vegetables",
  "Light breaking into many colors as it passes through a prism",
  "The Great Stone Face",
]

const SABIAN_ES: string[] = [
  // Aries 1-30
  "Una mujer ha surgido del océano, una foca la abraza",
  "Un comediante revela la naturaleza humana",
  "Un camafeo con el perfil de un hombre en el contorno de su país",
  "Dos amantes pasean por un sendero apartado",
  "Un triángulo con alas",
  "Un cuadrado brillantemente iluminado por un lado",
  "Un hombre logra expresarse en dos reinos al mismo tiempo",
  "El sombrero de una mujer con cintas agitadas por el viento del este",
  "Una vidente con bola de cristal",
  "Un hombre enseña nuevas formas para símbolos antiguos",
  "El gobernante de una nación",
  "Una bandada de gansos salvajes",
  "Una bomba que no explotó ahora está escondida con seguridad",
  "Una serpiente enroscada cerca de un hombre y una mujer",
  "Un indígena tejiendo una manta",
  "Duendecillos bailando en el sol poniente",
  "Dos solteronas remilgadas sentadas juntas en silencio",
  "Una hamaca vacía",
  "La alfombra mágica de la imaginería oriental",
  "Una joven alimentando pájaros en invierno",
  "Un púgil entrando al ring",
  "La puerta al jardín de todos los deseos cumplidos",
  "Una mujer en colores pastel cargando una pesada y valiosa carga velada",
  "Una ventana abierta y una cortina de tul soplando hacia un cuerno de la abundancia",
  "Una doble promesa revela sus significados interno y externo",
  "Un hombre poseído de más dones de los que puede expresar",
  "Mediante la imaginación se recupera una oportunidad perdida",
  "Un gran público decepcionado",
  "Un coro celestial cantando",
  "Un estanque de patos y su nidada",
  // Taurus 1-30
  "Un arroyo claro de montaña",
  "Una tormenta eléctrica",
  "Escalones naturales conducen a un prado de trébol en flor",
  "La olla de oro del arcoíris",
  "Una viuda ante una tumba abierta",
  "Un puente que se construye sobre un desfiladero",
  "Una mujer de Samaria viene a sacar agua",
  "Un trineo sin nieve",
  "Un árbol de Navidad completamente decorado",
  "El reflejo del ser de un hombre en el espejo quieto de un estanque",
  "Una mujer regando flores en su jardín",
  "Mirones de escaparates",
  "Un hombre manejando equipaje",
  "Mariscos tanteando y niños jugando",
  "Peces magnéticos bajo el hielo polar",
  "Un anciano intentando en vano revelar los misterios",
  "Una batalla simbólica entre espadas y antorchas",
  "Una mujer aireando una bolsa de lino por la ventana soleada",
  "Un continente recién formado",
  "Jirones de nubes aladas cruzando el cielo",
  "Un dedo señalando en un libro abierto",
  "Una paloma blanca sobre aguas turbulentas",
  "Una joyería",
  "Una joven indígena presenta a su amante blanco ante su tribu reunida",
  "Un vasto parque público",
  "Un español serenando a su amada",
  "Una indígena vendiendo cuentas",
  "Una mujer perseguida por un romance maduro",
  "Dos zapateros trabajando en una mesa",
  "Un pavo real desfilando en un antiguo prado",
  // Gemini 1-30
  "Un barco con fondo de vidrio revela maravillas submarinas",
  "Santa Claus llenando medias a hurtadillas",
  "El jardín de las Tullerías en París",
  "Acebo y muérdago reavivan viejos recuerdos navideños",
  "Una revista o publicación radical",
  "Perforando en busca de petróleo",
  "Un pozo antiguo con las aguas más puras y frías",
  "Huelguistas exaltados rodean una fábrica",
  "Un carcaj lleno de flechas",
  "Un avión en picada hacia la tierra",
  "Tierras recién abiertas ofrecen al pionero nuevas oportunidades de experiencia",
  "Una esclava negra exige sus derechos a su ama",
  "Un gran músico ante su piano",
  "Una conversación por telepatía",
  "Dos niños holandeses conversando e intercambiando conocimiento",
  "Una activista en un discurso emocional dramatizando su causa",
  "La cabeza de un joven robusto se transforma en la de un pensador maduro",
  "Dos figuras en la noche, una de ellas una silueta",
  "Un gran volumen arcaico revela sabiduría tradicional",
  "Una cafetería moderna muestra abundancia de productos de diversas regiones",
  "Una manifestación laboral",
  "Un baile en el granero",
  "Tres polluelos en un nido alto en un árbol",
  "Niños patinando sobre hielo",
  "Un hombre podando palmeras",
  "Árboles cubiertos de escarcha contra cielos invernales",
  "Una gitana emergiendo del bosque donde está acampada su tribu",
  "Mediante la quiebra la sociedad da a un individuo sobrecargado la oportunidad de empezar de nuevo",
  "El primer sinsonte de primavera",
  "Un desfile de bellezas en traje de baño ante grandes multitudes en la playa",
  // Cancer 1-30
  "En un barco los marineros bajan una bandera vieja y izan una nueva",
  "Un hombre en una alfombra mágica sobrevuela una gran extensión de tierra",
  "Un explorador ártico conduce un reno por cañones helados",
  "Un gato discutiendo con un ratón",
  "Un automóvil destrozado por un tren",
  "Aves de caza emplumando sus nidos",
  "Dos hadas en una noche de luna",
  "Conejos vestidos con ropa y en desfile",
  "Una pequeña desnuda alcanzando un pez en el agua",
  "Un gran diamante no completamente tallado",
  "Un payaso caricaturizando personalidades conocidas",
  "Una mujer china amamantando un bebé cuya aura revela que es la reencarnación de un gran maestro",
  "Una mano ligeramente flexionada con un pulgar muy prominente",
  "Un anciano muy viejo frente a un vasto espacio oscuro al noreste",
  "En un suntuoso comedor los invitados descansan tras un gran banquete",
  "Un hombre ante un cuadrado con un manuscrito enrollado frente a él",
  "La semilla crece en conocimiento y vida",
  "Una gallina escarbando el suelo para alimentar a su progenie",
  "Un sacerdote celebrando una ceremonia de matrimonio",
  "Gondoleros en una serenata",
  "Una famosa cantante demuestra su virtuosismo en una ópera",
  "Una joven esperando un velero",
  "Reunión de una sociedad literaria",
  "Una mujer y dos hombres náufragos en una pequeña isla del mar del Sur",
  "Un fuego fatuo",
  "Contento y felicidad en el lujo: gente montando en un carrusel",
  "Una tormenta en un cañón",
  "Una Pocahontas moderna",
  "Una musa pesando gemelos",
  "Una hija de la Revolución Americana",
  // Leo 1-30
  "Bajo estrés emocional la sangre sube a la cabeza de un hombre",
  "Una epidemia de paperas",
  "Una mujer haciéndose el peinado",
  "Un anciano vestido formalmente y una joven",
  "Formaciones rocosas se elevan sobre un cañón profundo",
  "Una dama conservadora y anticuada es confrontada por una chica hippie",
  "Las constelaciones brillan intensamente en el cielo nocturno",
  "Un propagandista bolchevique",
  "Sopladores de vidrio dan forma a hermosos jarrones con su respiración controlada",
  "El rocío de la mañana brilla mientras el sol inunda el campo",
  "Niños jugando en un columpio colgado de las ramas de un gran roble",
  "Una fiesta vespertina en el césped para adultos",
  "Un viejo capitán de mar meciendo en el porche de su cabaña",
  "El alma humana, ávida de nuevas experiencias, busca encarnación",
  "Un desfile",
  "Sol brillante justo después de una tormenta",
  "Un coro voluntario de iglesia hace un evento social del ensayo",
  "Un profesor de química",
  "Una fiesta en una casa flotante",
  "Los adoradores del sol zuni",
  "Gallinas embriagadas",
  "Una paloma mensajera cumpliendo su misión",
  "Un jinete sin silla en un circo",
  "Totalmente concentrado en la realización espiritual interior, un hombre está sentado en completo descuido de su apariencia y limpieza corporal",
  "Un gran camello cruzando un vasto y temible desierto",
  "Tras las tormentas del invierno, una serena escena primaveral se representa",
  "Amanecer: la luminosidad del alba en el cielo oriental",
  "Muchos pajaritos en una rama de un gran árbol",
  "Una sirena emerge de las olas del océano lista para renacer en forma humana",
  "Una carta sin sellar",
  // Virgo 1-30
  "En un retrato, los rasgos significativos de la cabeza de un hombre están artísticamente enfatizados",
  "Una gran cruz blanca alzada",
  "Dos ángeles trayendo protección",
  "Un niño de color jugando con niños blancos",
  "Un hombre soñando con hadas",
  "Un carrusel",
  "Un harén",
  "Primera clase de baile",
  "Un hombre haciendo un dibujo futurista",
  "Dos cabezas mirando hacia afuera y más allá de las sombras",
  "Un niño moldeado por las aspiraciones de su madre para él",
  "Una novia con el velo arrancado",
  "Una mano fuerte suplanta la histeria política",
  "Un árbol genealógico",
  "Un fino pañuelo de encaje ornamental",
  "Un orangután",
  "Una erupción volcánica",
  "Una tabla ouija",
  "Una carrera de natación",
  "Una caravana de autos rumbo a la costa oeste",
  "Un equipo de baloncesto femenino",
  "Un escudo de armas real",
  "Un domador de leones se lanza sin miedo al ruedo del circo",
  "María y su corderito blanco",
  "Una bandera a media asta frente a un gran edificio público",
  "Un niño con incensario sirve al sacerdote cerca del altar",
  "Señoras ancianas aristocráticas tomando té de la tarde en una casa rica",
  "Un hombre calvo que ha tomado el poder",
  "Un hombre ganando conocimiento secreto de un antiguo pergamino que lee",
  "Una falsa llamada no oída por atención al servicio inmediato",
  // Libra 1-30
  "En una colección de especímenes perfectos de muchas formas biológicas, una mariposa muestra la belleza de sus alas que varían del tipo general",
  "La luz de la sexta raza transmutada a la séptima",
  "El amanecer de un nuevo día revela todo cambiado",
  "Un grupo de jóvenes sentados en comunión espiritual alrededor de una fogata",
  "Un hombre enseñando el verdadero conocimiento interior del nuevo mundo a sus alumnos",
  "Los ideales de un hombre abundantemente cristalizados",
  "Una mujer alimentando gallinas y protegiéndolas de los halcones",
  "Una chimenea ardiente en una casa desierta",
  "Tres viejos maestros colgados en una sala especial de una galería de arte",
  "Habiendo pasado sanamente por rápidos estrechos, una canoa llega a aguas calmadas",
  "Un profesor mirando por encima de sus gafas a sus alumnos",
  "Mineros emergiendo de una mina de carbón profunda",
  "Niños soplando burbujas de jabón",
  "Una siesta al mediodía",
  "Caminos circulares",
  "Tras una tormenta un muelle necesita reconstrucción",
  "Un capitán de mar retirado observa barcos entrando y saliendo del puerto",
  "Dos hombres arrestados rinden cuentas de sus actos ante el tribunal de la sociedad",
  "Una banda de ladrones escondidos",
  "Un rabino cumpliendo sus deberes",
  "Una multitud en la playa",
  "Un niño dando de beber a pájaros en una fuente",
  "La voz de Chanticleer anuncia el sol naciente con exuberancia",
  "Una mariposa con un tercer ala en su lado izquierdo",
  "La vista de una hoja otoñal trae a un peregrino la repentina revelación del misterio de la vida y la muerte",
  "Un águila y una gran paloma blanca transformándose una en la otra",
  "Un avión navega alto en el cielo claro",
  "Un hombre en profunda tristeza. Sin ser notados, ángeles vienen en su ayuda",
  "La humanidad buscando tender el puente del conocimiento",
  "Tres montones de conocimiento en la cabeza de un filósofo",
  // Scorpio 1-30
  "Un autobús turístico abarrotado en una calle de la ciudad",
  "Una delicada botella de perfume yace rota, liberando su fragancia",
  "Una fiesta de construcción de casas en una comunidad americana antigua presta su esfuerzo para edificar la casa de un hombre",
  "Un joven llevando una vela encendida",
  "Una costa rocosa masiva",
  "Una fiebre del oro arranca a los hombres de su suelo natal",
  "Buzos de aguas profundas",
  "La luna plateada brillando sobre una hermosa joya de lago",
  "Un dentista trabajando",
  "Una cena de confraternidad reúne viejos camaradas",
  "Un hombre que se ahoga está siendo rescatado",
  "Un baile de embajada",
  "Un inventor realiza un experimento de laboratorio",
  "Linieros telefónicos trabajando instalando nuevas conexiones",
  "Niños jugando alrededor de cinco montones de arena",
  "El rostro de una niña rompiendo en una sonrisa",
  "Una mujer fecundada por su propio espíritu está 'grávida'",
  "Un bosque rico en colores otoñales",
  "Un loro escuchando y luego hablando, repite una conversación que ha oído",
  "Una mujer aparta dos cortinas oscuras que cierran la entrada a un camino sagrado",
  "Obedeciendo su conciencia, un soldado resiste órdenes",
  "Cazadores saliendo en busca de patos",
  "Un conejito transformado en hada",
  "Multitudes bajando de la montaña para escuchar a un solo hombre",
  "Una fotografía de rayos X",
  "Indígenas acampando en nuevo territorio",
  "Una banda militar en marcha",
  "El rey de las hadas acercándose a su dominio",
  "Una indígena suplicando al jefe por la vida de sus hijos",
  "El bufón de Halloween",
  // Sagittarius 1-30
  "Veteranos retirados del ejército se reúnen para revivir viejos recuerdos",
  "El océano cubierto de cabrillas blancas",
  "Dos hombres jugando ajedrez",
  "Un niño pequeño aprendiendo a caminar con el aliento de sus padres",
  "Un viejo búho en un árbol",
  "Un partido de críquet",
  "Cupido llamando a la puerta",
  "En las profundidades de la tierra se forman nuevos elementos",
  "Una madre con sus hijos en las escaleras",
  "Una representación teatral de una diosa rubia de la oportunidad",
  "La lámpara de la iluminación física en la sien izquierda",
  "Una bandera que se transforma en un águila que canta",
  "El pasado de una viuda sale a la luz",
  "Las pirámides y la esfinge",
  "La marmota buscando su sombra el día de la marmota",
  "Gaviotas observando un barco",
  "Un servicio de amanecer de Pascua atrae a una gran multitud",
  "Niños pequeños con gorros de sol",
  "Pelícanos amenazados por el comportamiento y desechos de los hombres buscan zonas más seguras para criar a sus crías",
  "En un pueblo norteño antiguo los hombres hacen rodar la pesada piedra",
  "Un niño y un perro con gafas prestadas",
  "Un general aceptando la derrota con elegancia",
  "Inmigrantes entrando a un nuevo país",
  "Un pájaro azul parado en la puerta de la casa",
  "Un niño regordete en un caballito de juguete",
  "Un portador de bandera en una batalla",
  "Un escultor en su trabajo",
  "Un viejo puente sobre un hermoso arroyo sigue en uso constante",
  "Un niño gordo cortando el césped",
  "El Papa bendiciendo a los fieles",
  // Capricorn 1-30
  "Un jefe indígena reclama poder ante la tribu reunida",
  "Tres vitrales en una iglesia gótica, uno dañado por la guerra",
  "El alma humana receptiva al crecimiento y la comprensión",
  "Un grupo de personas equipando una gran canoa al inicio de un viaje por agua",
  "Indígenas: algunos remando una canoa y otros bailando una danza de guerra en ella",
  "Diez troncos yacen bajo un arco que lleva a bosques más oscuros",
  "Un profeta velado habla, poseído por el poder de un dios",
  "En un hogar soleado, aves domésticas cantan alegremente",
  "Un ángel llevando un arpa",
  "Un albatros alimentándose de la mano de un marinero",
  "Un gran grupo de faisanes en una finca privada",
  "Una conferencia ilustrada sobre ciencias naturales revela aspectos poco conocidos de la vida",
  "Un adorador del fuego medita sobre las realidades últimas de la existencia",
  "Un antiguo bajorrelieve tallado en granito permanece como testigo de una cultura olvidada hace tiempo",
  "En un hospital, la sala infantil está llena de juguetes",
  "Niños y niñas en trajes de gimnasia",
  "Una mujer reprimida encuentra liberación psicológica en el nudismo",
  "La bandera Union Jack ondea en un nuevo buque de guerra británico",
  "Un niño de unos cinco años con una enorme bolsa de compras",
  "Un coro oculto cantando durante un servicio religioso",
  "Una carrera de relevos",
  "Aceptando la derrota con elegancia, un general revela nobleza de carácter",
  "Dos condecoraciones por valentía en la guerra",
  "Una mujer entrando a un convento",
  "Un comerciante de alfombras orientales en una tienda llena de preciosas alfombras ornamentales",
  "Un espíritu del agua",
  "Peregrinos subiendo los empinados escalones hacia un santuario en la montaña",
  "Un gran aviario",
  "Una mujer leyendo las hojas de té",
  "Una conferencia de negocios secreta",
  // Aquarius 1-30
  "Una antigua misión de adobe en California",
  "Una tormenta inesperada",
  "Un desertor de la marina",
  "Un pandit hindú revela su casta por sus sandalias",
  "Un consejo de ancestros ha sido convocado para guiar a un hombre",
  "Un intérprete de una obra de misterio",
  "Se ve a un niño naciendo de un huevo",
  "Figuras de cera elegantemente vestidas en exhibición",
  "Se ve una bandera transformarse en un águila",
  "Un hombre que por un tiempo encarnó un ideal popular se da cuenta de que como persona no es ese ideal",
  "Durante una hora silenciosa, un hombre recibe una nueva inspiración que puede cambiar su vida",
  "Gente en escaleras ascendiendo gradualmente",
  "Un barómetro",
  "Un tren entrando en un túnel",
  "Dos tórtolos sentados en una cerca y cantando felices",
  "Un gran hombre de negocios en su escritorio",
  "Un vigilante señalando en la noche",
  "Un hombre desenmascarado",
  "Un incendio forestal es dominado con agua, químicos y pura energía muscular",
  "Una gran paloma blanca portando un mensaje",
  "Una mujer decepcionada y desilusionada enfrentando con coraje una vida aparentemente vacía",
  "Una alfombra colocada en el suelo para que jueguen los niños",
  "Un gran oso sentado agitando todas sus patas",
  "Un hombre dando la espalda a sus pasiones enseña desde su experiencia",
  "Una mariposa con el ala derecha más perfectamente formada",
  "Un hidrómetro",
  "Un antiguo cuenco de cerámica lleno de violetas frescas",
  "Un árbol talado y aserrado para asegurar suministro de leña para el invierno",
  "Mariposa emergiendo de la crisálida",
  "Campos iluminados por la luna, que una vez fueron Babilonia, ahora florecen en blanco",
  // Pisces 1-30
  "Un mercado público",
  "Una ardilla escondiéndose de los cazadores",
  "Un hombre penitente confesando sus pecados a un sacerdote",
  "Tráfico pesado en un estrecho istmo",
  "Un bazar de iglesia",
  "Oficiales en desfile de gala",
  "Iluminada por un rayo de luz, una gran cruz yace sobre rocas rodeada de niebla marina y pequeñas olas con crestas blancas",
  "Una niña tocando una corneta",
  "Comienza la carrera: con intención de superar a sus rivales, un jinete espolea su caballo a gran velocidad",
  "Un aviador en las nubes",
  "Hombres buscando iluminación se esfuerzan por penetrar los misterios, sentados en círculo usando una tabla ouija",
  "En el santuario de una hermandad oculta, nuevos miembros iniciados son examinados y su carácter probado",
  "Una espada usada en muchas batallas ahora está en un museo",
  "Una mujer envuelta en piel de zorro",
  "Un oficial preparando hombres para un largo viaje por tierra",
  "En la quietud de su estudio un individuo creativo experimenta un flujo de inspiración",
  "Un paseo de Pascua",
  "En una enorme carpa un famoso revivalista dirige su reunión con una actuación espectacular",
  "Un maestro instruyendo a sus discípulos",
  "Una mesa puesta para la cena vespertina",
  "Bajo la mirada vigilante y bondadosa de un sirviente chino, una niña acaricia un pequeño corderito blanco",
  "La puerta al jardín del deseo",
  "Un médium 'materializador' dando una sesión",
  "En una pequeña isla rodeada por la vasta extensión del mar, la gente hace una barbacoa junto al agua",
  "La purga del sacerdocio",
  "Observando la delgada luna creciente apareciendo al atardecer, diferentes personas se dan cuenta de que ha llegado el momento de avanzar con sus distintos proyectos",
  "La luna de la cosecha ilumina un claro cielo otoñal",
  "Un jardín fértil bajo la luna llena revela una variedad de vegetales maduros",
  "La luz descomponiéndose en muchos colores al pasar por un prisma",
  "El Gran Rostro de Piedra",
]

const SABIAN_SYMBOLS: Record<Lang, string[]> = {
  en: SABIAN_EN,
  es: SABIAN_ES,
}

export function getSabianSymbol(
  longitude: number,
  lang: Lang = 'en'
): { degree: number; symbol: string; signDegree: string } {
  const normalized = ((longitude % 360) + 360) % 360
  // Sabian symbols are 1-360, where degree 0°00'-0°59' = symbol 1
  const index = Math.floor(normalized)
  const SIGN_NAMES: Record<Lang, string[]> = {
    en: ['Aries','Taurus','Gemini','Cancer','Leo','Virgo',
         'Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'],
    es: ['Aries','Tauro','Géminis','Cáncer','Leo','Virgo',
         'Libra','Escorpio','Sagitario','Capricornio','Acuario','Piscis'],
  }
  const signIndex  = Math.floor(index / 30)
  const degInSign  = (index % 30) + 1
  return {
    degree:     index + 1,
    symbol:     SABIAN_SYMBOLS[lang][index] ?? SABIAN_SYMBOLS['en'][index] ?? 'Symbol not found',
    signDegree: `${SIGN_NAMES[lang][signIndex]} ${degInSign}°`,
  }
}
